services:
    w3all.displayonlyfirstpost.controller.acp:
        class: w3all\displayonlyfirstpost\controller\acp_controller
        arguments:
            - '@config_text'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'

    w3all.displayonlyfirstpost.listener:
        class: w3all\displayonlyfirstpost\event\main_listener
        arguments:
            - '@config_text'
            - '@language'
        tags:
            - { name: event.listener }
